name: hoge

on:
  push:
    branches:
      - master
      - hoge
  pull_request:
    branches:
      - master
      - hoge

jobs:
  hoge:
    runs-on: ubuntu-latest
    steps:
      - name: hoge
        run: git log
